// # ฺB1. Mock data from PartB_Q1_In.txt file 
export const PRODUCT_LIST = [
  { title: "iPhone 15", stock: 120, price: 999, type: "electronics", isOnline: true },
  { title: "MacBook Pro", stock: 45, price: 1999, type: "electronics", isOnline: true },
  { title: "AirPods Pro", stock: 200, price: 249, type: "electronics", isOnline: false },
  { title: "Office Chair", stock: 85, price: 180, type: "furniture", isOnline: true },
  { title: "Standing Desk", stock: 30, price: 450, type: "furniture", isOnline: false },
  { title: "Bookshelf", stock: 60, price: 120, type: "furniture", isOnline: true },
  { title: "Running Shoes", stock: 150, price: 95, type: "fashion", isOnline: true },
  { title: "Denim Jacket", stock: 70, price: 130, type: "fashion", isOnline: false },
  { title: "Baseball Cap", stock: 220, price: 35, type: "fashion", isOnline: true },
  { title: "Protein Powder", stock: 90, price: 55, type: "health", isOnline: true },
  { title: "Vitamin C", stock: 300, price: 20, type: "health", isOnline: true },
  { title: "Yoga Mat", stock: 110, price: 40, type: "health", isOnline: false },
  { title: "Coffee Beans", stock: 180, price: 25, type: "grocery", isOnline: true },
  { title: "Olive Oil", stock: 75, price: 18, type: "grocery", isOnline: false },
  { title: "Organic Honey", stock: 50, price: 22, type: "grocery", isOnline: true },
  { title: "LEGO City Set", stock: 95, price: 60, type: "toys", isOnline: true },
  { title: "Remote Control Car", stock: 40, price: 85, type: "toys", isOnline: false },
  { title: "Puzzle 1000 pcs", stock: 130, price: 30, type: "toys", isOnline: true }
];



// # B2. Mock data from PartB_Q2_In file 
export const RAW_USERS = [
  {
    firstName: "Brian",
    lastName: "Smith",
    email: "brian.smith2@example.com",
    phone: "084-111-2222",
    age: 31,
    city: "Bangkok",
    isActive: true,
    tags: ["control"],
    createdAt: "2024-08-20"
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    email: "ALICE.JOHNSON@EXAMPLE.COM",
    phone: "(+66) 8-7654-3210",
    age: 24,
    city: "Chiang Mai",
    isActive: false,
    tags: ["test-record"],
    createdAt: "2024-06-01"
  },
  {
    firstName: "Grace",
    lastName: "Brown",
    email: "grace.brown+test@example.com",
    phone: "0812345678",
    age: 26,
    city: "Phuket",
    isActive: true,
    tags: ["test"],
    createdAt: "2023-03-25"
  },
  {
    firstName: "Daniel",
    lastName: "Kim",
    email: "daniel.kim@example.com",
    phone: "089-123-4567",
    age: 35,
    city: "Nonthaburi",
    isActive: true,
    tags: ["lead"],
    createdAt: "2021-12-02"
  },
  {
    firstName: "Frank",
    lastName: "Miller",
    email: "FRANK.MILLER@example.com",
    phone: "02-1234-5678",
    age: 29,
    city: "Bangkok",
    isActive: false,
    tags: ["duplicate-email-case"],
    createdAt: "2023-07-14"
  },
  {
    firstName: "Catherine",
    lastName: "Lee",
    email: "catherine.lee@EXAMPLE.com",
    phone: "061-234-5678",
    age: 27,
    city: "Bangkok",
    isActive: false,
    tags: ["archived"],
    createdAt: "2024-03-05"
  },
  {
    firstName: "Karen",
    lastName: "Anderson",
    email: "karen.anderson@example.com",
    phone: "08-4321-0000",
    age: 30,
    city: "Bangkok",
    isActive: true,
    tags: ["support"],
    createdAt: "2023-01-03"
  },
  {
    firstName: "Isabella",
    lastName: "Moore",
    email: "isabella.moore@example.com",
    phone: "099-999-9999",
    age: 28,
    city: "Bangkok",
    isActive: true,
    tags: ["product"],
    createdAt: "2022-02-11"
  },
  {
    firstName: "Brian",
    lastName: "Smith",
    email: "brian.alt@example.com",
    phone: "092-345-6789",
    age: 31,
    city: "Bangkok",
    isActive: true,
    tags: [],
    createdAt: "2024-01-12"
  },
  {
    firstName: "Alice",
    lastName: "Johnston",
    email: "alice.johnston@example.com",
    phone: "0876543210",
    age: 24,
    city: "Chiang Mai",
    isActive: true,
    tags: ["control"],
    createdAt: "2024-07-08"
  },
  {
    firstName: "Henry",
    lastName: "Wilson",
    email: "henry.wilson@example.com",
    phone: "(+66) 9-1111-2222",
    age: 33,
    city: "Chiang Rai",
    isActive: true,
    tags: ["security"],
    createdAt: "2021-11-19"
  },
  {
    firstName: "Emma",
    lastName: "Williams",
    email: "emma.williams@example.com",
    phone: "0971112233",
    age: 22,
    city: "Khon Kaen",
    isActive: true,
    tags: ["new"],
    createdAt: "2024-09-10"
  },
  {
    firstName: "Daniel",
    lastName: "Kim",
    email: "daniel.kim+spam@example.com",
    phone: "(+66) 8-9123-4567",
    age: 35,
    city: "Nonthaburi",
    isActive: true,
    tags: ["ops"],
    createdAt: "2023-04-16"
  },
  {
    firstName: "Karen",
    lastName: "Anderson",
    email: "karen.alt@example.com",
    phone: "(+66) 8-4321-0000",
    age: 30,
    city: "Bangkok",
    isActive: false,
    tags: ["duplicate-phone"],
    createdAt: "2023-02-14"
  },
  {
    firstName: "Grace",
    lastName: "Brown",
    email: "grace.brown@example.com",
    phone: "08-1234-5678",
    age: 26,
    city: "Phuket",
    isActive: true,
    tags: ["sales"],
    createdAt: "2023-03-22"
  },
  {
    firstName: "Emma",
    lastName: "Williams",
    email: "emma.williams+promo@example.com",
    phone: "097-111-2233",
    age: 22,
    city: "Khon Kaen",
    isActive: false,
    tags: ["promo"],
    createdAt: "2024-10-01"
  },
  {
    firstName: "Frank",
    lastName: "Miller",
    email: "frank.miller@example.com",
    phone: "02-1234-5678",
    age: 29,
    city: "Bangkok",
    isActive: true,
    tags: ["qa"],
    createdAt: "2022-05-30"
  },
  {
    firstName: "Catherine",
    lastName: "Lee",
    email: "catherine.lee@example.com",
    phone: "0612345678",
    age: 27,
    city: "Bangkok",
    isActive: true,
    tags: ["design"],
    createdAt: "2022-08-21"
  },
  {
    firstName: "Isabella",
    lastName: "Moore",
    email: "ISABELLA.MOORE@EXAMPLE.COM",
    phone: "099-999-9990",
    age: 28,
    city: "Bangkok",
    isActive: false,
    tags: ["duplicate-email-case"],
    createdAt: "2024-05-19"
  },
  {
    firstName: "Jack",
    lastName: "Taylor",
    email: "jack.taylor@example.com",
    phone: "02-2222-3333",
    age: 34,
    city: "Bangkok",
    isActive: true,
    tags: ["engineering"],
    createdAt: "2020-09-07"
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    phone: "08-0000-0000",
    age: 24,
    city: "Chiang Mai",
    isActive: true,
    tags: ["vip", "newsletter"],
    createdAt: "2024-02-18"
  },
  {
    firstName: "Brian",
    lastName: "Smith",
    email: "BRIAN.SMITH@example.com",
    phone: "(+66) 9-2345-6789",
    age: 31,
    city: "Bangkok",
    isActive: true,
    tags: ["beta"],
    createdAt: "2023-10-09"
  }
];


// # B3 Mock data from PartB_Q3 file
export const USER_DATA = [
  { id: 1, name: "Alice Johnson", email: "alice.johnson@example.com", age: 22, role: "Intern" },
  { id: 2, name: "Brian Smith", email: "brian.smith@example.com", age: 25, role: "Frontend Developer" },
  { id: 3, name: "Catherine Lee", email: "catherine.lee@example.com", age: 28, role: "UI/UX Designer" },
  { id: 4, name: "Daniel Kim", email: "daniel.kim@example.com", age: 31, role: "Backend Developer" },
  { id: 5, name: "Emma Williams", email: "emma.williams@example.com", age: 24, role: "QA Engineer" },
  { id: 6, name: "Frank Miller", email: "frank.miller@example.com", age: 35, role: "Project Manager" },
  { id: 7, name: "Grace Brown", email: "grace.brown@example.com", age: 27, role: "Product Designer" },
  { id: 8, name: "Henry Wilson", email: "henry.wilson@example.com", age: 29, role: "DevOps Engineer" },
  { id: 9, name: "Isabella Moore", email: "isabella.moore@example.com", age: 23, role: "Intern" },
  { id: 10, name: "Jack Taylor", email: "jack.taylor@example.com", age: 34, role: "Tech Lead" },
  { id: 11, name: "Karen Anderson", email: "karen.anderson@example.com", age: 26, role: "Frontend Developer" },
  { id: 12, name: "Leo Thomas", email: "leo.thomas@example.com", age: 32, role: "Backend Developer" },
  { id: 13, name: "Mia Jackson", email: "mia.jackson@example.com", age: 21, role: "Intern" },
  { id: 14, name: "Noah White", email: "noah.white@example.com", age: 28, role: "QA Engineer" },
  { id: 15, name: "Olivia Harris", email: "olivia.harris@example.com", age: 30, role: "Product Owner" },
  { id: 16, name: "Paul Martin", email: "paul.martin@example.com", age: 36, role: "Engineering Manager" },
  { id: 17, name: "Quinn Thompson", email: "quinn.thompson@example.com", age: 27, role: "UI/UX Designer" },
  { id: 18, name: "Rachel Garcia", email: "rachel.garcia@example.com", age: 24, role: "Frontend Developer" },
  { id: 19, name: "Samuel Martinez", email: "samuel.martinez@example.com", age: 33, role: "Backend Developer" },
  { id: 20, name: "Tina Robinson", email: "tina.robinson@example.com", age: 29, role: "Scrum Master" },
  { id: 21, name: "Uma Clark", email: "uma.clark@example.com", age: 26, role: "QA Engineer" },
  { id: 22, name: "Victor Rodriguez", email: "victor.rodriguez@example.com", age: 38, role: "System Architect" },
  { id: 23, name: "Wendy Lewis", email: "wendy.lewis@example.com", age: 31, role: "Business Analyst" },
  { id: 24, name: "Xavier Lee", email: "xavier.lee@example.com", age: 28, role: "Mobile Developer" },
  { id: 25, name: "Yara Walker", email: "yara.walker@example.com", age: 23, role: "Intern" },
  { id: 26, name: "Zach Hall", email: "zach.hall@example.com", age: 35, role: "DevOps Engineer" },
  { id: 27, name: "Aaron Young", email: "aaron.young@example.com", age: 27, role: "Frontend Developer" },
  { id: 28, name: "Bella King", email: "bella.king@example.com", age: 25, role: "Content Designer" },
  { id: 29, name: "Chris Wright", email: "chris.wright@example.com", age: 34, role: "Backend Developer" },
  { id: 30, name: "Diana Lopez", email: "diana.lopez@example.com", age: 29, role: "QA Engineer" },
  { id: 31, name: "Ethan Hill", email: "ethan.hill@example.com", age: 22, role: "Intern" },
  { id: 32, name: "Fiona Scott", email: "fiona.scott@example.com", age: 31, role: "Product Manager" },
  { id: 33, name: "George Green", email: "george.green@example.com", age: 37, role: "Security Engineer" },
  { id: 34, name: "Hannah Adams", email: "hannah.adams@example.com", age: 26, role: "Frontend Developer" },
  { id: 35, name: "Ian Baker", email: "ian.baker@example.com", age: 33, role: "Backend Developer" },
  { id: 36, name: "Julia Nelson", email: "julia.nelson@example.com", age: 28, role: "UI/UX Designer" },
  { id: 37, name: "Kevin Carter", email: "kevin.carter@example.com", age: 35, role: "Tech Lead" },
  { id: 38, name: "Laura Mitchell", email: "laura.mitchell@example.com", age: 24, role: "QA Engineer" },
  { id: 39, name: "Mark Perez", email: "mark.perez@example.com", age: 30, role: "Backend Developer" },
  { id: 40, name: "Nina Roberts", email: "nina.roberts@example.com", age: 27, role: "Frontend Developer" },
  { id: 41, name: "Oscar Turner", email: "oscar.turner@example.com", age: 39, role: "CTO" },
  { id: 42, name: "Paula Phillips", email: "paula.phillips@example.com", age: 34, role: "HR Manager" },
  { id: 43, name: "Ryan Campbell", email: "ryan.campbell@example.com", age: 29, role: "DevOps Engineer" },
  { id: 44, name: "Sophia Parker", email: "sophia.parker@example.com", age: 23, role: "Intern" },
  { id: 45, name: "Tom Evans", email: "tom.evans@example.com", age: 32, role: "Backend Developer" },
  { id: 46, name: "Ursula Edwards", email: "ursula.edwards@example.com", age: 28, role: "QA Engineer" },
  { id: 47, name: "Victor Collins", email: "victor.collins@example.com", age: 36, role: "Platform Engineer" },
  { id: 48, name: "Will Stewart", email: "will.stewart@example.com", age: 31, role: "Product Manager" },
  { id: 49, name: "Xena Morris", email: "xena.morris@example.com", age: 26, role: "Frontend Developer" },
  { id: 50, name: "Yusuf Rogers", email: "yusuf.rogers@example.com", age: 34, role: "Backend Developer" },
  { id: 51, name: "Zoe Reed", email: "zoe.reed@example.com", age: 22, role: "Intern" },
  { id: 52, name: "Adam Cook", email: "adam.cook@example.com", age: 29, role: "QA Engineer" },
  { id: 53, name: "Bianca Morgan", email: "bianca.morgan@example.com", age: 27, role: "UI Designer" },
  { id: 54, name: "Caleb Bell", email: "caleb.bell@example.com", age: 35, role: "Infrastructure Engineer" },
  { id: 55, name: "Denise Murphy", email: "denise.murphy@example.com", age: 31, role: "Business Analyst" },
  { id: 56, name: "Elliot Bailey", email: "elliot.bailey@example.com", age: 24, role: "Frontend Developer" },
  { id: 57, name: "Farah Cooper", email: "farah.cooper@example.com", age: 28, role: "QA Engineer" },
  { id: 58, name: "Gavin Richardson", email: "gavin.richardson@example.com", age: 37, role: "Solutions Architect" },
  { id: 59, name: "Hailey Cox", email: "hailey.cox@example.com", age: 26, role: "Product Designer" },
  { id: 60, name: "Ivan Howard", email: "ivan.howard@example.com", age: 33, role: "Backend Developer" },
  { id: 61, name: "Jasmine Ward", email: "jasmine.ward@example.com", age: 25, role: "Frontend Developer" },
  { id: 62, name: "Kyle Brooks", email: "kyle.brooks@example.com", age: 34, role: "DevOps Engineer" },
  { id: 63, name: "Liam Foster", email: "liam.foster@example.com", age: 29, role: "QA Engineer" },
  { id: 64, name: "Megan Price", email: "megan.price@example.com", age: 32, role: "Product Manager" }
];
